### ISSUE TITLE
Deployed project early

### ISSUE THREAD

**Issue by victormc13** [victormc13/victormc13.github.io#1]
### Live demo of the deployed project:
---
- https://victormc13.github.io/

**Comment by Shisui6** [comment]
Hi @victormc13, 

# Approved 🪄
Your project is complete! Congratulations! 🎉 

## Highlights
- App deployed properly ✅

Cheers and Happy coding!🍻💻

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
